fixed for shellcheck.net

diff --git a/buildj b/buildj
--- a/buildj
+++ b/buildj
@@ -22,20 +22,20 @@ isJVM ()
 
 createJar()
 {
-  cd $proj || echo "cannot cd to $proj";
+  cd "$proj" || echo "cannot cd to $proj";
   jarFile="$proj-$version.jar"
-  if [ ! -e $manifestFile ] 
+  if [ ! -e "$manifestFile" ] 
   then
     echo "$manifestFile does not exist. Run ant manifest in $proj."
     exit 1
   fi
-  jar cfm $jarFile $manifestFile \
-    `find . -name "*.class" \
-    ! -path "*.git*" -type f` || \
+  jar cfm "$jarFile" "$manifestFile" \
+    $(find . -name "*.class" \
+    ! -path "*.git*" -type f) || \
     { echo "Error creating jar output: $jarFile";exit 1; }
   jarRes=$? 
-  [ -e $jarFile ] && cp $jarFile .. \
-    && mkdir -p $distDir && mv $jarFile $distDir || \
+  [ -e "$jarFile" ] && cp "$jarFile" .. \
+    && mkdir -p "$distDir" && mv "$jarFile" "$distDir" || \
     { echo "Error moving jar file to $proj/$distDir"; }
   cd ..
   exit 0
@@ -43,15 +43,15 @@ createJar()
 
 readVersion()
 {
-  [ -e $versionFile ] && \
-      { version=$(cat $versionFile) || \
+  [ -e "$versionFile" ] && \
+      { version=$(cat "$versionFile") || \
       echo "Unable to read $versionFile";}
 }
 
 readOptions()
 {
-  [ -e $proj/$optionsFile ] && \
-      { options=$(cat $proj/$optionsFile) || \
+  [ -e "$proj"/"$optionsFile" ] && \
+      { options=$(cat "$proj"/"$optionsFile") || \
       echo "Unable to read $proj/$optionsFile";}
 }
 
@@ -71,18 +71,18 @@ declare -i SUCCESS=0
 isJVM
 jvm=$?
 jarRes=0
-if [ -z $proj ] || [ ! -d $proj ]
+if [ -z "$proj" ] || [ ! -d "$proj" ]
   then
     usage
 else
-    echo $proj
-    [ -e $proj/$verFile ] && \
-      { ver=$(cat $proj/$verFile) || \
-      echo $verErrMsg;}
+    echo "$proj"
+    [ -e "$proj"/"$verFile" ] && \
+      { ver=$(cat "$proj"/"$verFile") || \
+      echo "$verErrMsg";}
     readOptions
-    javac $options -source $ver -target $ver \
-    -cp $proj -Xlint:all \
-    `find $proj -name "*.java" -type f`
+    javac $options -source "$ver" -target "$ver" \
+    -cp "$proj" -Xlint:all \
+    $(find "$proj" -name "*.java" -type f)
     success=$?
     if [[ $success -eq SUCCESS ]]
       then
@@ -91,9 +91,9 @@ else
         then
         createJar
       else
-        echo $archiveErrMsg
+        echo "$archiveErrMsg"
         success=1
       fi
     fi
 fi
-exit `expr $success + $jarRes`
+exit $(expr $success + $jarRes)
