fix: fix shellcheck warnings

diff --git a/ckjm b/ckjm
--- a/ckjm
+++ b/ckjm
@@ -24,14 +24,15 @@ fi
 echo "$1"
 proj="$1"
 
+# shellcheck disable=SC2155
 classpath="$(cat "$classpathFile"):."
 res="$(cd "$proj" || exit $?
 java -cp "$classpath" \
     "$mainClass" \
     "$(find . -name '*.class')" \
     | tee "$outputFile" \
-    || { exitCode="$?";echo "$0 exited with error code $exitCode";cd ..; exit "$exitCode";}
-res=$?
+    || { exitCode="$?";echo "$0 exited with error code $exitCode";exit "$exitCode";}
+  )"
 echo "ClassName WMC DIT NOC CBO RFC LCOM Ca Ce NPM LCOM3 LOC DAM MOA MFA CAM IC CBM AMC" > "$conciseFile"
 grep '^[^[:space:]]\{1\}' "$outputFile" >> "$conciseFile"
 exit "$res"
