chore(deps): update lizard script

diff --git a/lizardcpd b/lizardcpd
--- a/lizardcpd
+++ b/lizardcpd
@@ -1,12 +1,15 @@
 #!/usr/bin/env bash
 require() {
-hash "$@" || exit 127;
+  hash "$@" || exit 127
 }
-require lizard find tee
+require lizard find tee paste
 declare -r errFile="lizardcpd.errors"
 
 lizard -w -Eduplicate \
-  "$(find . -name '*.java')" \
-  | tee "$errFile" \
-  || { echo "Error running $0"; exit 1;}
+  "$(find . -name '*.java' | paste -sd ' ')" |
+  tee "$errFile" ||
+  {
+    echo "Error running $0"
+    exit 1
+  }
 exit $?
