chore(deps): update lizard script

diff --git a/lizardtagcloud b/lizardtagcloud
--- a/lizardtagcloud
+++ b/lizardtagcloud
@@ -1,9 +1,12 @@
 #!/usr/bin/env bash
 require() {
-hash "$@" || exit 127;
+  hash "$@" || exit 127
 }
-require lizard find
-lizard -w -EWordCount \
-  "$(find . -name '*.java')" \
-  || { echo "Errors/warnings found running $0"; exit 1;}
+require lizard find paste
+lizard -Ewordcount \
+  "$(find . -name '*.java' | paste -sd ' ')" ||
+  {
+    echo "Errors/warnings found running $0"
+    exit 1
+  }
 exit $?
