Add changes to support external jars in auxclasspath for pmd

diff --git a/pmdaux b/pmdaux
--- a/pmdaux
+++ b/pmdaux
@@ -16,6 +16,8 @@ readExclusions()
 declare -r rulesFile="pmdrules.xml"
 declare -r cacheFile="pmd.cache"
 declare -r errFile="pmd.errors"
+declare -r auxCpFile="pmdaux.cp"
+declare -r setupcp="setupclasspath"
 declare -r format="text"
 declare -i threads=5
 declare -i minpriority=5
@@ -36,9 +38,26 @@ readExclusions
 set -o noglob
 cd "$proj"
 rm ./"$fileslist"
+if [ -s "$setupcp" ]
+then
+  ./"$setupcp"
+fi
 find . -type f -regex ".*[.]\(java\|jsp\)$" ${exclusions[@]} | tr '\n' ',' > "$fileslist"
 if [ -s "$fileslist" ]
 then
+if [ -s "$auxCpFile" ]
+then
+  java -cp @../"$classpathFile" \
+    "$mainClass" \
+    -filelist "$fileslist" -R ../"$rulesFile" -f "$format" \
+    -min "$minpriority" -norulesetcompatibility \
+    -failOnViolation true -cache "$cacheFile" \
+    -reportfile "$errFile" \
+    -auxclasspath file://$(realpath "$auxCpFile") \
+    -t "$threads" \
+    || { exitCode="$?";echo "$0 exited with error code $exitCode"; exit "$exitCode";}
+      res=$?
+    else
       java -cp @../"$classpathFile" \
     "$mainClass" \
     -filelist "$fileslist" -R ../"$rulesFile" -f "$format" \
@@ -49,6 +68,7 @@ then
     -t "$threads" \
     || { exitCode="$?";echo "$0 exited with error code $exitCode"; exit "$exitCode";}
       res=$?
+fi
 fi
 set +o noglob
 exit $res
