Added tests to runtermux

diff --git a/runtermux b/runtermux
--- a/runtermux
+++ b/runtermux
@@ -30,6 +30,20 @@ setUp ()
 	cd ..
 }
 
+tests ()
+{
+	cd "$proj" || \
+    { echo "Unable to access folder $proj";exit 1;}
+	[ -e "$testsScript" ] && \
+    { ./"$testsScript" || \
+      { \
+        echo "Error running tests script";\
+        exit 1;\
+      }\
+    }
+	cd ..
+}
+
 tearDown ()
 {
 	cd "$proj" || \
@@ -68,6 +82,10 @@ runDalvik()
       echo
     done
     tearDown;
+    if [[ ${#main[@]} > 1 ]]
+    then
+      tests;
+    fi
     exit 0;
   else
     echo "$dexFile does not exist. Run build or buildall."
@@ -90,6 +108,7 @@ readRunOptions()
 }
 
 declare -r setupScript="setup"
+declare -r testsScript="tests"
 declare -r teardownScript="teardown"
 declare -r nomainFile=".nomain"
 declare -r mainFile=".main"
@@ -110,9 +129,11 @@ declare -r versionFile=".version"
 declare -r runOptionsFile=".runoptions"
 declare -a runOptions
 version="0.0.0"
-main[0]="$2"
-if [ -z "$2" ]
+if [ "$#" -ge 2 ]
 then
+  printf -v params "%s " "${@:2}"
+  main[0]="$params"
+else
   readarray main < "$proj"/"$mainFile" || \
     { echo "Error reading $proj/$mainFile";usage; }
 fi
