fix: use readlink to make cmd executable from anywhere

diff --git a/spotbugscmd b/spotbugscmd
--- a/spotbugscmd
+++ b/spotbugscmd
@@ -1,19 +1,25 @@
 #!/usr/bin/env bash
+# shellcheck disable=SC2155
 require() {
-hash "@" || exit 127
+  hash "@" || exit 127
 }
-require java cat realpath 
-# shellcheck disable=SC2155
-declare -r classpathFile="$(realpath 'spotbugs.cp')"
-# shellcheck disable=SC2155
+path() {
+  dirname "$(readlink -f "$1")"
+}
+require java cat readlink dirname
+declare -i res=0
+declare -r classpathFile="$(path 'spotbugs.cp')"
 declare -r classpath="$(cat "$classpathFile")"
 declare -r mainClass="edu.umd.cs.findbugs.LaunchAppropriateUI"
 declare -r pluginjars="spotbugs-plugin.cp"
-# shellcheck disable=SC2155
 declare -r plugins="$(cat "$pluginjars")"
 
 java -cp "$classpath" "$mainClass" \
-  -pluginList "<${plugins}>" "$@" \
-|| { exitCode="$?";echo "$0 exited with error code $exitCode"; exit "$exitCode";}
+  -pluginList "<${plugins}>" "$@" ||
+  {
+    exitCode="$?"
+    echo "$0 exited with error code $exitCode"
+    exit "$exitCode"
+  }
 res=$?
 exit $res
