Modify spotbugs

diff --git a/spotbugs b/spotbugs
--- a/spotbugs
+++ b/spotbugs
@@ -7,28 +7,39 @@ usage()
 }
 
 declare -r errFile="spotbugs.errors"
-declare -r classpathFile="spotbugs.cp"
+declare -r classpathFile=$(realpath "spotbugs.cp")
+declare -r setupCpFile="setupclasspath"
+declare -r auxCpFile="compile.cp"
+auxCp=""
 declare -r suppressionsFile="suppressions-sb.xml"
 declare -r mainClass="edu.umd.cs.findbugs.LaunchAppropriateUI"
-declare -r pluginjars="spotbugs-plugin.cp"
+declare -r pluginjars=$(realpath "spotbugs-plugin.cp")
+plugincp=$(cat "$pluginjars" | tr -d \')
 
 if [ "$#" -ne 1 ] || ! [ -d "$1" ]; 
 then
   usage
 fi
 
-echo "$1"
-./buildj "$1"
+proj="$1"
+echo "$proj"
+./buildj "$proj"
+cd "$proj"
+if [ -e "$setupCpFile" ]
+then
+  ./"$setupCpFile"
+  auxCp=$(cat "$auxCpFile")
+fi
 java -cp @"$classpathFile" "$mainClass" \
-  -output "$1"/"$errFile" \
-  -auxclasspath "$1" -quiet -adjustExperimental \
+  -output "$errFile" \
+  -auxclasspath "$auxCp":. -quiet -adjustExperimental \
   -workHard \
   -experimental -nested:true -timestampNow \
   -longBugCodes -progress -dontCombineWarnings \
-  -pluginList '<$(cat "$pluginjars")>' \
-  -exclude "$1"/"$suppressionsFile" \
-  "$1" \
-|| { exitCode="$?";echo "$0 exited with error code $exitCode"; exit "$exitCode";}
+  -pluginList "$plugincp" \
+  -exclude "$suppressionsFile" \
+  . \
+|| { exitCode="$?";echo "$0 exited with error code $exitCode"; cd ..; exit "$exitCode";}
 res=$?
+cd ..
 exit $res
-
