chore(deps): update dependency org.springframework.boot:spring-boot to v3.0.2

diff --git a/git/hooks/pre-commit b/git/hooks/pre-commit
--- a/git/hooks/pre-commit
+++ b/git/hooks/pre-commit
@@ -6,15 +6,14 @@
 # it wants to stop the commit.
 #
 require() {
-hash "$@" || exit 127;
+  hash "$@" || exit 127
 }
-require git cat find head tidy rm 
-if git rev-parse --verify HEAD >/dev/null 2>&1
-then
-	against=HEAD
+require git cat find head tidy rm
+if git rev-parse --verify HEAD >/dev/null 2>&1; then
+  against=HEAD
 else
-	# Initial commit: diff against an empty tree object
-	against=$(git hash-object -t tree /dev/null)
+  # Initial commit: diff against an empty tree object
+  against=$(git hash-object -t tree /dev/null)
 fi
 
 # If you want to allow non-ASCII filenames set this variable to true.
@@ -27,13 +26,12 @@ exec 1>&2
 # them from being added to the repository. We exploit the fact that the
 # printable range starts at the space character and ends with tilde.
 if [ "$allownonascii" != "true" ] &&
-	# Note that the use of brackets around a tr range is ok here, (it's
-	# even required, for portability to Solaris 10's /usr/bin/tr), since
-	# the square bracket bytes happen to fall in the designated range.
-	test "$(git diff --cached --name-only --diff-filter=A -z "$against" |
-	  LC_ALL=C tr -d '[ -~]\0' | wc -c)" != 0
-then
-	cat <<\EOF
+  # Note that the use of brackets around a tr range is ok here, (it's
+  # even required, for portability to Solaris 10's /usr/bin/tr), since
+  # the square bracket bytes happen to fall in the designated range.
+  test "$(git diff --cached --name-only --diff-filter=A -z "$against" |
+    LC_ALL=C tr -d '[ -~]\0' | wc -c)" != 0; then
+  cat <<\EOF
 Error: Attempt to add a non-ASCII file name.
 
 This can cause problems if you want to work with people on other platforms.
@@ -44,7 +42,7 @@ If you know what you are doing you can disable this check using:
 
   git config hooks.allownonascii true
 EOF
-	exit 1
+  exit 1
 fi
 
 # If there are whitespace errors, print the offending file names and fail.
@@ -52,8 +50,8 @@ fi
 
 declare -r configFileName="tidy.config"
 configFilePath="$(find .. -maxdepth 2 \
--type f -name "$configFileName" ! -path \
-"**/.git/**" | head -n 1)"
+  -type f -name "$configFileName" ! -path \
+  "**/.git/**" | head -n 1)"
 
 # Regexp for grep to only choose some file extensions for formatting
 exts="\.xml$"
@@ -62,28 +60,26 @@ exts="\.xml$"
 formatter=$(which tidy)
 
 # Check availability of the formatter
-if [ -z "$formatter" ]
-then
-  1>&2 echo "$formatter not found. Pre-commit formatting will not be done."
+if [ -z "$formatter" ]; then
+  echo 1>&2 "$formatter not found. Pre-commit formatting will not be done."
   exit 0
 fi
 
 files="$(git diff --cached --name-only --diff-filter=ACMR | grep $exts)"
 # Format staged files
-for file in $files
-do
+for file in $files; do
   # don't format empty files
   if test -s "$file"; then
     echo "Formatting $file"
     # Get the file from index
-    git show ":$file" > "${file}.tmp"
+    git show ":$file" >"${file}.tmp"
     # Format it
     "$formatter" -config "$configFilePath" -quiet -xml -m -i "${file}.tmp"
     # Create a blob object from the formatted file
     hash=$(git hash-object -w "${file}.tmp")
     # Add it back to index
     git update-index --add --cacheinfo 100644 "$hash" "$file"
-    git cat-file -p "$hash" > "${file}"
+    git cat-file -p "$hash" >"${file}"
     rm "${file}.tmp"
   fi
 done
@@ -91,14 +87,14 @@ done
 # If no files left in index after formatting - fail
 ret=0
 diffs="$(git diff --cached --name-only)"
+echo "$diffs"
 if [ ! "$diffs" ]; then
-	if test -z "$files";
-	then
-    1>&2 echo "No xml files staged"
+  if test -z "$files"; then
+    echo 1>&2 "No xml files staged"
     exit 0
   else
-    1>&2 echo "No files left after formatting"
+    echo 1>&2 "No files left after formatting"
     exit 1
-	fi
+  fi
 fi
 exit "$ret"
